ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM kibana:8.6.2
#docker.elastic.co/kibana/kibana:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
