ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM elasticsearch:8.6.2
#docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
